fix(package): check dump function before loading manager

diff --git a/scripts/package/dump b/scripts/package/dump
--- a/scripts/package/dump
+++ b/scripts/package/dump
@@ -39,16 +39,23 @@ for package_manager in $(package::get_available_package_managers); do
 
   if
     [[ $package_manager == "npm" ]] &&
-      package::get_available_package_managers | grep -q "^volta$" ||
-      ! package::command_exists "$package_manager" "dump"
+      package::get_available_package_managers | grep -q "^volta$"
   then
     continue
   fi
 
-  {
-    package::command_exists "$package_manager" "dump" &&
-      package::load_manager "$package_manager" &&
+  if ! package::command_exists "$package_manager" "dump" 2> /dev/null; then
+    continue
+  fi
+
+  package::load_manager "$package_manager" || {
+    output::error "Error while loading $(eval echo "\$${package_manager}_title")" &&
       output::empty_line &&
+      continue
+  }
+
+  {
+    output::empty_line &&
       output::h2 "🚀 Starting $(eval echo "\$${package_manager}_title") apps dump" &&
       package::command "$package_manager" "dump" "$dump_file_path" &&
       output::answer "$(eval echo "\$${package_manager}_title") apps dumped on \`${dump_file_path}\`" &&
